"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-16 19:37:56.947468

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models.base import JSONType

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('before', JSONType, nullable=True),
    sa.Column('after', JSONType, nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=40), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_workflow_run_id'), ['workflow_run_id'], unique=False)
        batch_op.create_index('ix_activity_ts', ['timestamp'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', JSONType, nullable=False),
    sa.Column('preview', JSONType, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', JSONType, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_templates_type'), ['type'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=100), nullable=True),
    sa.Column('attendance_rules', JSONType, nullable=False),
    sa.Column('attendance_sheet_id', sa.String(length=100), nullable=True),
    sa.Column('attendance_sheet_tab', sa.String(length=100), nullable=True),
    sa.Column('feedback_form_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('context', JSONType, nullable=False),
    sa.Column('pause_reason', sa.String(length=100), nullable=True),
    sa.Column('resume_token', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('completed_steps', JSONType, nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('events', JSONType, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('zoom_meeting_id', sa.String(length=50), nullable=True),
    sa.Column('zoom_meeting_uuid', sa.String(length=100), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=False),
    sa.Column('planned_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('trainees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('zoom_aliases', JSONType, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainees_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainees_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=True),
    sa.Column('zoom_name', sa.String(length=200), nullable=True),
    sa.Column('zoom_email', sa.String(length=200), nullable=True),
    sa.Column('zoom_user_id', sa.String(length=100), nullable=True),
    sa.Column('raw_intervals', JSONType, nullable=False),
    sa.Column('merged_intervals', JSONType, nullable=False),
    sa.Column('total_minutes', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('first_join', sa.DateTime(), nullable=True),
    sa.Column('last_leave', sa.DateTime(), nullable=True),
    sa.Column('disconnect_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('flags', JSONType, nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('suggestions', JSONType, nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'trainee_id', name='uq_session_trainee')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_att_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_session_id'), ['session_id'], unique=False)

    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('msg_type', sa.String(length=50), nullable=False),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('rendered_subject', sa.String(length=300), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('provider_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_messages_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_trainee_id'), ['trainee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_messages_trainee_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_approval_id'))

    op.drop_table('outbound_messages')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_needs_review'))
        batch_op.drop_index('ix_att_session_status')

    op.drop_table('attendance_records')
    with op.batch_alter_table('trainees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainees_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_trainees_program_id'))
        batch_op.drop_index(batch_op.f('ix_trainees_email'))

    op.drop_table('trainees')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_program_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_definition'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_programs_status'))

    op.drop_table('programs')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_type'))
        batch_op.drop_index(batch_op.f('ix_message_templates_tenant_id'))

    op.drop_table('message_templates')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_type'))
        batch_op.drop_index(batch_op.f('ix_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_status'))

    op.drop_table('approvals')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_ts')
        batch_op.drop_index(batch_op.f('ix_activity_log_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
